### ISSUE TITLE
Missende EditorConfig veroorzaakt problemen met Windows hosts

### ISSUE THREAD

**Issue by sanmai-NL** [hanaim-webtech/webtech-is-env#1]
Doordat de [`.editorconfig`](https://github.com/hanaim-webtech/WT_IS_Bp/blob/8f8edad8613ef3e15239493ef24c4feefda1a67f/.editorconfig) is weggelaten uit deze template, werken shell scripts niet meer als ze onder de Windows host worden aangepast en opgeslagen. Windows gebruikt andere regeleindes dan Linux, en Linux weigert bijv. `/root/provision.sh` uit te voeren als de regeleindes niet kloppen.

**Comment by sanmai-NL** [comment]
Ontwikkelaars (de facto: zowel studenten als docenten) moeten ook de [EditorConfig extension](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) aan hebben staan in hun VS Code vóór ze tekstbestanden aanpassen vanaf een niet-Unix host zoals Windows.

**Comment by fritzvd** [comment]
Interessant. Ik heb dit gisteren op windows gedraaid.. weird. Dank je in ieder geval!

**Comment by sanmai-NL** [comment]
Een student liep er weer tegenaan. 
![image](https://user-images.githubusercontent.com/3374183/100755762-d1cb6b80-33ec-11eb-9d4d-3702b5f667f3.png)

Een ontbrekende schakel is het voorkomen dat Git de regeleindes automatisch Windows-only maakt als je clonet onder Windows. Dit heb ik opgelost in https://github.com/hanaim-webtech/webtech-is-env/commit/a3f48b86dfcc44bccf29baa97d99973d14b0a75c.

Als we actief hadden voorkomen dat studenten zelf Git gebruiken, was dit nooit een probleem geworden trouwens. Belangrijk om bij stil te staan (@bartvanderwal).
