### ISSUE TITLE
Poortnummer in launch.json komt niet overeen met poortnummer in docker-compose.yml

### ISSUE THREAD

**Issue by PeterSchulzNL** [hanaim-webtech/webtech-is-env#2]
De url in de launch.json wijst naar poort 8080 en in docker-compose.yml naar 8000. S.v.p. even gelijk maken. THX

**Comment by fritzvd** [comment]
Dank je. Wil het ook graag doen. Ik weet niet zo goed welke launch.json je bedoelt 💁‍♂️ .

**Comment by sanmai-NL** [comment]
Dit is toch het verkeerde GitHub-project. Ik heb een [`launch.json`](https://github.com/hanaim-webtech/WT_IS_Bp/blob/a0537660b695e09e60ec42f17e1b88a5b1ae03b0/webserver/.vscode/launch.json). Het poortnummer daarin is afwijkend, omdat dit niet de HTTP-poort maar een debuggerservicepoort is.
